// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcZ1tgTS1SECOdxbnoHI1hkx0tL1gX1tc',
    appId: '1:804327651648:web:af5260473acdffc2a962a5',
    messagingSenderId: '804327651648',
    projectId: 'clothing-9d79e',
    authDomain: 'clothing-9d79e.firebaseapp.com',
    storageBucket: 'clothing-9d79e.firebasestorage.app',
    measurementId: 'G-C2TL1F439P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCSI-0UBbwRBez9ta9w0cRya14yLbOhuQ',
    appId: '1:804327651648:android:e1e4c02319540955a962a5',
    messagingSenderId: '804327651648',
    projectId: 'clothing-9d79e',
    storageBucket: 'clothing-9d79e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJHDkz93K0Jbr3AaA6ezRr1HnIk4w7lzk',
    appId: '1:804327651648:ios:fc35b0f73d2435dea962a5',
    messagingSenderId: '804327651648',
    projectId: 'clothing-9d79e',
    storageBucket: 'clothing-9d79e.firebasestorage.app',
    iosBundleId: 'com.favour.clothing.clothingapp',
  );
}
